### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by andreaspenz** [oroinc/environment#1]
When i try to run the tests (except unit-tests) following your documentation (https://github.com/oroinc/environment/blob/master/doc/TESTING.md) i get the following error:

> Pulling data-cache (oroinc/data-cache:latest)...  
ERROR: repository oroinc/data-cache not found: does not exist or no pull access  

Is it possible that this is a private docker-repo?

**Comment by sergeyz** [comment]
Hi, @andreaspenz, let me check it shortly

**Comment by sergeyz** [comment]
Repository available again https://hub.docker.com/r/oroinc/data-cache 
In addition, new images pushed to the hub, feel free to test it and provide us a feedback, thank you.
