### ISSUE TITLE
typo error in composer image

### ISSUE THREAD

**Issue by AdriwanKenoby** [oroinc/environment#4]
In `compser/conf/docker-entrypoint-wrapper.sh` you check the existence of `${DEBUG}` variable however in Dockerfile or in composer.yml you declare a variable name `SYMFONY_DEBUG` which I think is the one you want check.

**Comment by dxops** [comment]
Hi, @AdriwanKenoby 

They are slightly different. SYMFONY_DEBUG enables debug for Symfony framework https://symfony.com/doc/2.8/configuration/environments.html#selecting-the-environment-for-console-commands and DEBUG variables used for bash commands debug http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_02_03.html
