### ISSUE TITLE
Consumer expects symfony 3.x directory path

### ISSUE THREAD

**Issue by dewos** [oroinc/environment#6]
https://github.com/oroinc/environment/blob/a66685a41dd4b602ce6a975d855f68e322dd0dc1/consumer/conf/consumer.sh#L42

**Comment by pedrofurtado** [comment]
This also happens in `2.6` branch of this repo. The file in repo is correct (https://github.com/oroinc/environment/blob/2.6/consumer/conf/consumer.sh), but the image hosted in Docker Hub contains the other version of file with the `bin/console`. Related to #7

**Comment by pedrofurtado** [comment]
A possible to solution is to tag the docker images of Oro for versions 2.6.x and 3.x, and update the repo in order to the branch 2.6 get only the images compatible with the 2.6.x versions, and so on.

**Comment by dewos** [comment]
@pedrofurtado a better solution could be a new ENV.

Like SYMFONY_CONSOLE = app/console

**Comment by pedrofurtado** [comment]
@dewos That is also another possible solution, that not involves any changes (at least for now) in Docker Oro Images.

**Comment by pedrofurtado** [comment]
@anyt @mbessolov Did you got simulate this bug?

**Comment by anyt** [comment]
Hi, 

I'm currently working on the configuration that can work with both directory structures, so developers will don't need to set any env vars or decide what version of VM to download for different application versions

**Comment by pedrofurtado** [comment]
@anyt Thanks for feedback! That's great, thanks again! :tada: 
Any news about this, let us know, and I'll be able to help you testing something :+1:

**Comment by pedrofurtado** [comment]
A temporary workaround is execute the following commands:

```bash
$ docker container exec oro_consumer_1 sed -i "s/php bin/php app/g" /usr/local/bin/consumer.sh
$ docker container restart oro_consumer_1
```
